services:
  - type: web
    name: employeedatamanager
    runtime: image  # Using image runtime
    image: pankaj2004/employeedatamanager:latest  # Specify image with tag (e.g., latest)
    plan: free
    branch: main
