services:
  - type: web
    name: employeedatamanager
    runtime: docker
    dockerfilePath: ./src/main/webapp/Dockerfile  # Path to your Dockerfile
    dockerContext: ./  # Context for building the Docker image
    dockerCommand: catalina.sh run  # Command to start the container
    plan: free
    branch: main
