services:
  - type: web
    name: employeedatamanager
    runtime: image
    buildCommand: 'echo "No build step required for .war"'
    startCommand: 'docker build -t my-app . && docker run -p 8080:8080 my-app'
    plan: free
    branch: main

